// Package execode GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package execode

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "get the status of server.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Show the status of server.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.healthCheck.response"
                        }
                    }
                }
            }
        },
        "/classes": {
            "get": {
                "description": "Gets all classes, set page size and page number through query parameters.",
                "tags": [
                    "Classes"
                ],
                "summary": "Gets all classes (paged)",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page size to return",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Page to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Describes the result of the execution",
                        "schema": {
                            "$ref": "#/definitions/api.GetClassesHandler.response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates the class defined by the request, the classes will be lectured by the specified lecturers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Classes"
                ],
                "summary": "Creates the class defined by the request",
                "parameters": [
                    {
                        "description": "Description of the class to created",
                        "name": "ClassDescription",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateClassHandler.request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Describes the created class",
                        "schema": {
                            "$ref": "#/definitions/api.CreateClassHandler.response"
                        }
                    }
                }
            }
        },
        "/classes/{ClassID}/lectures": {
            "get": {
                "tags": [
                    "Lectures"
                ],
                "summary": "Get lectures belonging to class",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Class ID to query",
                        "name": "ClassID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Describes lecture created",
                        "schema": {
                            "$ref": "#/definitions/api.GetClassLecturesHandler.response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/classes/{ClassID}/problems": {
            "get": {
                "tags": [
                    "Lectures"
                ],
                "summary": "Get lectures belonging to class",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Class ID to query",
                        "name": "ClassID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Describes lecture created",
                        "schema": {
                            "$ref": "#/definitions/api.GetClassProblemsHandler.response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/classes/{classID}": {
            "get": {
                "description": "Gets all classes, set page size and page number through query parameters.",
                "tags": [
                    "Classes"
                ],
                "summary": "Gets all classes (paged)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of class to return",
                        "name": "classID",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Describes the result of the execution",
                        "schema": {
                            "$ref": "#/definitions/api.GetClassesHandler.response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Classes"
                ],
                "summary": "Delete class specified by class_id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of class to delete",
                        "name": "ClassID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Describes the result of the execution",
                        "schema": {
                            "$ref": "#/definitions/api.DeleteClassHandler.response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/execute": {
            "post": {
                "description": "Execute the code in the language specified in the POST request body.\nIf it is a submission task then save user submissions as well.",
                "consumes": [
                    "application/json",
                    "text/xml"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Execute"
                ],
                "summary": "Execute code and handle user submissions.",
                "parameters": [
                    {
                        "description": "Description of the job to be run",
                        "name": "JobDescription",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ExecutionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Describes the result of the execution",
                        "schema": {
                            "$ref": "#/definitions/ExecutionResults"
                        }
                    }
                }
            }
        },
        "/execute/runtimes": {
            "get": {
                "description": "Get all available language runtimes provided by the connected piston instance",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Execute"
                ],
                "summary": "List installed Piston runtimes.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PistonRuntimeList"
                        }
                    }
                }
            }
        },
        "/lectures": {
            "post": {
                "tags": [
                    "Lectures"
                ],
                "summary": "Create lecture for class specified by class_id",
                "parameters": [
                    {
                        "description": "Describes lecture to be created",
                        "name": "LectureDescription",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateLectureHandler.request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Describes lecture created",
                        "schema": {
                            "$ref": "#/definitions/api.CreateLectureHandler.response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lectures/{LectureID}": {
            "get": {
                "tags": [
                    "Lectures"
                ],
                "summary": "Get Lecture specified by lecture_id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "LectureID to get",
                        "name": "LectureID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Describes lecture created",
                        "schema": {
                            "$ref": "#/definitions/api.GetLectureHandler.response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Lectures"
                ],
                "summary": "Get Lecture specified by lecture_id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "LectureID to get",
                        "name": "LectureID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Describes lecture created",
                        "schema": {
                            "$ref": "#/definitions/api.GetLectureHandler.response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Authenticates with basic authentication return a JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Login endpoint",
                "parameters": [
                    {
                        "description": "Description of the user to created",
                        "name": "loginCredentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginHandler.request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Describes the created user",
                        "schema": {
                            "$ref": "#/definitions/auth.BearerToken"
                        }
                    }
                }
            }
        },
        "/problems": {
            "get": {
                "description": "Gets all classes, set page size and page number through query parameters.",
                "tags": [
                    "Problems"
                ],
                "summary": "Gets all classes (paged)",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page size to return",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Page to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Describes the result of the execution",
                        "schema": {
                            "$ref": "#/definitions/api.GetProblemsHandler.response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "Problems"
                ],
                "summary": "Create lecture for class specified by class_id",
                "parameters": [
                    {
                        "description": "Describes lecture to be created",
                        "name": "ProblemDescription",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateProblemHandler.request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Describes lecture created",
                        "schema": {
                            "$ref": "#/definitions/api.CreateProblemHandler.response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/problems/{ProblemID}": {
            "get": {
                "tags": [
                    "Problems"
                ],
                "summary": "Get Lecture specified by lecture_id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "LectureID to get",
                        "name": "ProblemID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Describes lecture created",
                        "schema": {
                            "$ref": "#/definitions/api.GetLectureHandler.response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Problems"
                ],
                "summary": "Get Lecture specified by problem_id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ProblemID to delete",
                        "name": "ProblemID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Describes lecture created",
                        "schema": {
                            "$ref": "#/definitions/api.DeleteProblemHandler.response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/refresh": {
            "get": {
                "description": "Provides a new access token given that there is a valid refresh-token cookie",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Refresh endpoint",
                "responses": {
                    "200": {
                        "description": "Describes the created user",
                        "schema": {
                            "$ref": "#/definitions/auth.BearerToken"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Gets all users, set page size and page number through query parameters.",
                "tags": [
                    "Users"
                ],
                "summary": "Gets all users (paged)",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page size to return",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Page to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Describes the result of the execution",
                        "schema": {
                            "$ref": "#/definitions/UsersList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Creates the user defined by the request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Creates the user defined by the request",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Description of the user to created",
                        "name": "UserDescription",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Describes the created user",
                        "schema": {
                            "$ref": "#/definitions/CreateUserResult"
                        }
                    }
                }
            }
        },
        "/users/{userID}": {
            "get": {
                "description": "Queries only one user resulting from the specified username",
                "tags": [
                    "Users"
                ],
                "summary": "Gets single user defined by username parameter",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Username to query",
                        "name": "userID",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Describes the user entity",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/swaggercompat.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "$ref": "#/definitions/UserAdvanced"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/users/{userID}/classes": {
            "get": {
                "tags": [
                    "Classes"
                ],
                "summary": "Get user class specified by class_id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username of user to query",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Describes the result of the execution",
                        "schema": {
                            "$ref": "#/definitions/api.GetUserClassesHandler.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ClassBasic": {
            "type": "object",
            "properties": {
                "class_description": {
                    "type": "string"
                },
                "class_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "ClassBasicNoRelation": {
            "type": "object",
            "properties": {
                "class_description": {
                    "type": "string"
                },
                "class_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "ClassFields": {
            "type": "object",
            "properties": {
                "classDescription": {
                    "type": "string"
                },
                "className": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lectures": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Lecture"
                    }
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "CreateUser": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "CreateUserResult": {
            "type": "object",
            "properties": {
                "result": {
                    "$ref": "#/definitions/UserBasic"
                }
            }
        },
        "ExecutionInput": {
            "type": "object",
            "properties": {
                "args": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "stdin": {
                    "type": "string"
                }
            }
        },
        "ExecutionRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "inputs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ExecutionInput"
                    }
                },
                "language": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "ExecutionResult": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "output": {
                    "type": "string"
                },
                "signal": {
                    "type": "string"
                },
                "stderr": {
                    "type": "string"
                },
                "stdout": {
                    "type": "string"
                }
            }
        },
        "ExecutionResults": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/PistonError"
                    }
                },
                "run": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ExecutionResult"
                    }
                }
            }
        },
        "PistonError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer"
                }
            }
        },
        "PistonRuntime": {
            "type": "object",
            "properties": {
                "aliases": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "language": {
                    "type": "string"
                },
                "node": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "PistonRuntimeList": {
            "type": "object",
            "properties": {
                "runtimes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/PistonRuntime"
                    }
                }
            }
        },
        "UserAdvanced": {
            "type": "object",
            "properties": {
                "classes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ClassBasicNoRelation"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "UserBasic": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "UsersList": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/UserBasic"
                    }
                }
            }
        },
        "api.CreateClassHandler.request": {
            "type": "object",
            "properties": {
                "class_description": {
                    "type": "string"
                },
                "class_name": {
                    "type": "string"
                },
                "lecturers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.CreateClassHandler.response": {
            "type": "object",
            "properties": {
                "result": {
                    "$ref": "#/definitions/ClassBasic"
                }
            }
        },
        "api.CreateLectureHandler.request": {
            "type": "object",
            "properties": {
                "class_id": {
                    "type": "integer"
                },
                "lecture_content": {
                    "type": "string"
                },
                "lecture_description": {
                    "type": "string"
                },
                "lecture_name": {
                    "type": "string"
                }
            }
        },
        "api.CreateLectureHandler.response": {
            "type": "object",
            "properties": {
                "result": {
                    "$ref": "#/definitions/entities.APILectureAdvanced"
                }
            }
        },
        "api.CreateProblemHandler.request": {
            "type": "object",
            "properties": {
                "class_id": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "problem_name": {
                    "type": "string"
                },
                "testcases": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.TestCase"
                    }
                }
            }
        },
        "api.CreateProblemHandler.response": {
            "type": "object",
            "properties": {
                "result": {
                    "$ref": "#/definitions/entities.Problem"
                }
            }
        },
        "api.DeleteClassHandler.response": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "api.DeleteProblemHandler.response": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "api.GetClassLecturesHandler.response": {
            "type": "object",
            "properties": {
                "lectures": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.APILectureBasic"
                    }
                }
            }
        },
        "api.GetClassProblemsHandler.response": {
            "type": "object",
            "properties": {
                "problems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.APIProblemBasic"
                    }
                }
            }
        },
        "api.GetClassesHandler.response": {
            "type": "object",
            "properties": {
                "classes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ClassBasic"
                    }
                },
                "count": {
                    "type": "integer"
                }
            }
        },
        "api.GetLectureHandler.response": {
            "type": "object",
            "properties": {
                "result": {
                    "$ref": "#/definitions/entities.APILectureAdvanced"
                }
            }
        },
        "api.GetProblemsHandler.response": {
            "type": "object",
            "properties": {
                "classes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.APIProblemBasic"
                    }
                },
                "count": {
                    "type": "integer"
                }
            }
        },
        "api.GetUserClassesHandler.response": {
            "type": "object",
            "properties": {
                "classes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ClassBasic"
                    }
                }
            }
        },
        "auth.BearerToken": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "auth.LoginHandler.request": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "entities.APILectureAdvanced": {
            "type": "object",
            "properties": {
                "class_id": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lecture_content": {
                    "type": "string"
                },
                "lecture_description": {
                    "type": "string"
                },
                "lecture_name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "entities.APILectureBasic": {
            "type": "object",
            "properties": {
                "class_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "lecture_description": {
                    "type": "string"
                },
                "lecture_name": {
                    "type": "string"
                }
            }
        },
        "entities.APIProblemBasic": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "problem_name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "entities.Lecture": {
            "type": "object",
            "properties": {
                "class": {
                    "$ref": "#/definitions/ClassFields"
                },
                "classID": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lectureContent": {
                    "$ref": "#/definitions/entities.LectureContent"
                },
                "lectureDescription": {
                    "type": "string"
                },
                "lectureName": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "entities.LectureContent": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "lectureID": {
                    "type": "integer"
                }
            }
        },
        "entities.Problem": {
            "type": "object",
            "properties": {
                "class": {
                    "$ref": "#/definitions/ClassFields"
                },
                "classID": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "problemContent": {
                    "$ref": "#/definitions/entities.ProblemContent"
                },
                "problemName": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "entities.ProblemContent": {
            "type": "object",
            "properties": {
                "statement": {
                    "type": "string"
                },
                "testcases": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.TestCase"
                    }
                }
            }
        },
        "entities.TestCase": {
            "type": "object",
            "properties": {
                "input": {
                    "type": "string"
                },
                "output": {
                    "type": "string"
                }
            }
        },
        "main.healthCheck.response": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "swaggercompat.Response": {
            "type": "object",
            "properties": {
                "result": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Execode API",
	Description:      "API for Execode code learning environment",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
